//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Knikkerbaan_SCADA.ScadaServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Policy", Namespace="http://schemas.datacontract.org/2004/07/KnikkerBaanServer")]
    [System.SerializableAttribute()]
    public partial class Policy : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte PolicyModuleOneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte PolicyModuleThreeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte PolicyModuleTwoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte PolicyValueOneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte PolicyValueThreeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte PolicyValueTwoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte receiverAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte senderAddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte PolicyModuleOne {
            get {
                return this.PolicyModuleOneField;
            }
            set {
                if ((this.PolicyModuleOneField.Equals(value) != true)) {
                    this.PolicyModuleOneField = value;
                    this.RaisePropertyChanged("PolicyModuleOne");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte PolicyModuleThree {
            get {
                return this.PolicyModuleThreeField;
            }
            set {
                if ((this.PolicyModuleThreeField.Equals(value) != true)) {
                    this.PolicyModuleThreeField = value;
                    this.RaisePropertyChanged("PolicyModuleThree");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte PolicyModuleTwo {
            get {
                return this.PolicyModuleTwoField;
            }
            set {
                if ((this.PolicyModuleTwoField.Equals(value) != true)) {
                    this.PolicyModuleTwoField = value;
                    this.RaisePropertyChanged("PolicyModuleTwo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte PolicyValueOne {
            get {
                return this.PolicyValueOneField;
            }
            set {
                if ((this.PolicyValueOneField.Equals(value) != true)) {
                    this.PolicyValueOneField = value;
                    this.RaisePropertyChanged("PolicyValueOne");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte PolicyValueThree {
            get {
                return this.PolicyValueThreeField;
            }
            set {
                if ((this.PolicyValueThreeField.Equals(value) != true)) {
                    this.PolicyValueThreeField = value;
                    this.RaisePropertyChanged("PolicyValueThree");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte PolicyValueTwo {
            get {
                return this.PolicyValueTwoField;
            }
            set {
                if ((this.PolicyValueTwoField.Equals(value) != true)) {
                    this.PolicyValueTwoField = value;
                    this.RaisePropertyChanged("PolicyValueTwo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte receiverAddress {
            get {
                return this.receiverAddressField;
            }
            set {
                if ((this.receiverAddressField.Equals(value) != true)) {
                    this.receiverAddressField = value;
                    this.RaisePropertyChanged("receiverAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte senderAddress {
            get {
                return this.senderAddressField;
            }
            set {
                if ((this.senderAddressField.Equals(value) != true)) {
                    this.senderAddressField = value;
                    this.RaisePropertyChanged("senderAddress");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ScadaServiceReference.IScadaService")]
    public interface IScadaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScadaService/SetPolicy", ReplyAction="http://tempuri.org/IScadaService/SetPolicyResponse")]
        void SetPolicy(Knikkerbaan_SCADA.ScadaServiceReference.Policy policy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScadaService/SetPolicy", ReplyAction="http://tempuri.org/IScadaService/SetPolicyResponse")]
        System.Threading.Tasks.Task SetPolicyAsync(Knikkerbaan_SCADA.ScadaServiceReference.Policy policy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScadaService/GetCanMessages", ReplyAction="http://tempuri.org/IScadaService/GetCanMessagesResponse")]
        string[] GetCanMessages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScadaService/GetCanMessages", ReplyAction="http://tempuri.org/IScadaService/GetCanMessagesResponse")]
        System.Threading.Tasks.Task<string[]> GetCanMessagesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScadaService/GetPolicy", ReplyAction="http://tempuri.org/IScadaService/GetPolicyResponse")]
        Knikkerbaan_SCADA.ScadaServiceReference.Policy GetPolicy();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScadaService/GetPolicy", ReplyAction="http://tempuri.org/IScadaService/GetPolicyResponse")]
        System.Threading.Tasks.Task<Knikkerbaan_SCADA.ScadaServiceReference.Policy> GetPolicyAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScadaService/GetServerName", ReplyAction="http://tempuri.org/IScadaService/GetServerNameResponse")]
        string GetServerName();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IScadaService/GetServerName", ReplyAction="http://tempuri.org/IScadaService/GetServerNameResponse")]
        System.Threading.Tasks.Task<string> GetServerNameAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IScadaServiceChannel : Knikkerbaan_SCADA.ScadaServiceReference.IScadaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ScadaServiceClient : System.ServiceModel.ClientBase<Knikkerbaan_SCADA.ScadaServiceReference.IScadaService>, Knikkerbaan_SCADA.ScadaServiceReference.IScadaService {
        
        public ScadaServiceClient() {
        }
        
        public ScadaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ScadaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScadaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ScadaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SetPolicy(Knikkerbaan_SCADA.ScadaServiceReference.Policy policy) {
            base.Channel.SetPolicy(policy);
        }
        
        public System.Threading.Tasks.Task SetPolicyAsync(Knikkerbaan_SCADA.ScadaServiceReference.Policy policy) {
            return base.Channel.SetPolicyAsync(policy);
        }
        
        public string[] GetCanMessages() {
            return base.Channel.GetCanMessages();
        }
        
        public System.Threading.Tasks.Task<string[]> GetCanMessagesAsync() {
            return base.Channel.GetCanMessagesAsync();
        }
        
        public Knikkerbaan_SCADA.ScadaServiceReference.Policy GetPolicy() {
            return base.Channel.GetPolicy();
        }
        
        public System.Threading.Tasks.Task<Knikkerbaan_SCADA.ScadaServiceReference.Policy> GetPolicyAsync() {
            return base.Channel.GetPolicyAsync();
        }
        
        public string GetServerName() {
            return base.Channel.GetServerName();
        }
        
        public System.Threading.Tasks.Task<string> GetServerNameAsync() {
            return base.Channel.GetServerNameAsync();
        }
    }
}
